### ISSUE TITLE
virtual scrolling

### ISSUE THREAD

**Issue by martingg88** [germanysbestkeptsecret/Wookmark-jQuery#204] opened 2015-07-24 10:16 UTC
can it attach/detach off-screen element when scrolling up/down in order to improve performance?

**Comment by martingg88** [comment] 2015-07-25 15:09
any update on this issue?

**Comment by Sebobo** [comment] 2015-07-26 06:31
Hi,

this is not yet implemented. There was another issue for that.
Didn't have time yet to think about how I will integrate this.

**Comment by Sebobo** [comment] 2016-03-10 04:10
Duplicate of #174

**Closed by Sebobo** 2016-03-10 04:10 UTC
Labels: Feature, Question
