### ISSUE TITLE
Generated boxes 'jump' for a split second when it loads..

### ISSUE THREAD

**Issue by shannont** [germanysbestkeptsecret/Wookmark-jQuery#202] opened 2015-07-22 09:41 UTC
I am using Chrome on Mac and noticed that when the content is generated, the boxes seem to stick together as if they had no padding and then 'jump' outwards into their correct positions when loaded. It only happens for a split second but it's noticeable. Does anyone know what could be wrong?

I use the code like this:

                 (function ($) {
			      var wookmark;
			
			     
			        wookmark = new Wookmark('.tiles-wrap', {
			          container: $('.products'),
			          itemWidth: 250,
			          offset: 20,
			          align: 'center'
			      });
			       })(jQuery);

And the .products has this CSS:

                    .products{
	               width: 940px;
	               position: relative;
                     }

Is it something I am doing wrong? I run the jQuery right after the content HTML.

**Comment by Sebobo** [comment] 2015-07-26 06:34
Hi,

this happens currently when you use the css transitions.
The reason is that the elements initially have a position of 0:0 and then get the correct position and your browser wants to animate that.
This has worked before and I realised that few days ago too. Maybe a regression there.

I will mark this as need to be fixed.
Maybe this can easily be fixed with css but I have to check.

**Comment by Sebobo** [comment] 2016-03-10 04:05
This is now fixed in 2.1.0

**Closed by Sebobo** 2016-03-10 04:05 UTC
Labels: Bug
